[[redirects]]
  from = "/sites/docs/*"
  to = "https://sites-foundation.netlify.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/emails/docs/*"
  to = "https://foundation-emails.netlify.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "/building-blocks/*"
  to = "https://foundation-building-blocks.netlify.com/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"

[[redirects]]
  from = "https://marketing-foundation.netlify.com/*"
  to = "https://get.foundation/:splat"
  status = 301
  force = true
  [redirects.headers]
    X-From = "Netlify"
